### PR TITLE
[mysqldump] Updated Bitnami MariaDB chart version

### PR DESCRIPTION
**Pull request by cpjolly**
# Which chart

# What this PR does / why we need it
Bitnami have removed version 9 of the MariaDB Helm Chart and have replaced it with version 11.
Also, setting the dependency to 11.x.x rather than a specific number ensures that the latest version 11 commit is always used.  

# Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

# Special notes for your reviewer

# Checklist

- [ ] [DCO](https://github.com/kokuwaio/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] All variables are documented in the charts README

### CODE REVIEW

**Comment by cpjolly** [comment]
Hi @monotek 

- You want me to bump the version field from 5.0.0 to 5.0.1 or 5.1.0 or 6.0.0 ?
- The last change to appVersion was 2 years ago by you from 2.4.1 to 3.0.0. Do you want 3.0.1, 3.1.0 or 4.0.0 ?

**Comment by monotek** [comment]
Please follow: https://semver.org/

**Comment by cpjolly** [comment]
@monotek - I have tried to sign my commit. Apologies if this is incorrect.

**Review by monotek — CHANGES_REQUESTED** [review]
You can follow these instructions to get it fixed: https://github.com/kokuwaio/helm-charts/pull/110/checks?check_run_id=7178731068

**Review by monotek — APPROVED** [review]

**Comment by cpjolly** [comment]
many thanks @monotek

**Pull request merged**
