### PR TITLE
Suggest new defaults and update README

### PR DESCRIPTION
**Pull request by ernetas**
# Which chart
fluentd-elasticsearch

# What this PR does / why we need it
README mentions defaults that are not actually the defaults.

# Which issue this PR fixes
NA
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

# Special notes for your reviewer

# Checklist

- [x] [DCO](https://github.com/kokuwaio/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] All variables are documented in the charts README

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
It's not common for helmcharts to set the resources by default.

Maybe we should add the default note:
```
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
```

Where do you got your "defaults" from?

Imho having no cpu request is a bad idea as Kubernetes automatically sets the request to the  limit value. Therefore you instandly lose 1 usable cpu on every node even if your pod only needs 100m to run.

**Comment by ernetas** [comment]
> Where do you got your "defaults" from?

I took the defaults from: https://github.com/kokuwaio/helm-charts/blame/main/charts/fluentd-elasticsearch/README.md#L149-L152

It's not really a problem that this chart doesn't have resources defined, I just kind of assumed that it did, due to that README, so I think it would also be okay just changing README to avoid confusion.

Good call about limits. So... I guess sounds like README only change would be best, right?

**Review by monotek — CHANGES_REQUESTED** [review]
Yes, i guess changing the readme to have no predefined values would be best.
Maybe even only adding "resources" there, which is empty.

**Comment by sschnabe** [comment]
Stale.

**Pull request closed without merging**
